CREATE VIEW DVH_PROFILERING_KODEVERK AS (
  SELECT
    PROFILERING_KODE_ID,
    PROFILERING_KODE
  FROM BRUKER_PROFILERING_KODEVERK
);

CREATE VIEW DVH_BRUKER_PROFILERING AS (
  SELECT
    BRUKER_REGISTRERING_ID,
    PROFILERING_TYPE,
    VERDI
  FROM BRUKER_PROFILERING
);

CREATE VIEW DVH_BRUKER_REAKTIVERING AS (
  SELECT
    BRUKER_REAKTIVERING_ID,
    AKTOR_ID,
    REAKTIVERING_DATO
  FROM BRUKER_REAKTIVERING
);

CREATE VIEW DVH_BEGRUNNELSE_KODEVERK AS (
  SELECT
    BEGRUNNELSE_ID,
    BEGRUNNELSE_KODE
  FROM BEGRUNNELSE_KODEVERK
);