DROP VIEW DVH_BRUKER_REGISTRERING;
CREATE VIEW DVH_BRUKER_REGISTRERING AS (
  SELECT
    BRUKER_REGISTRERING_ID,
    AKTOR_ID,
    OPPRETTET_DATO,
    YRKESPRAKSIS,
    NUS_KODE,
    YRKESBESKRIVELSE,
    KONSEPT_ID,
    -1 as UTDANNING_BESTATT,
    -1 as UTDANNING_GODKJENT_NORGE,
    -1 as HELSE_UTFORDRINGER,
    -1 as ANDRE_UTFORDRINGER,
    'USIKKER_JOBBSITUASJON' as BEGRUNNELSE_FOR_REGISTRERING
  FROM BRUKER_REGISTRERING
);