CREATE TABLE BRUKER_PROFILERING_KODEVERK (
  PROFILERING_KODE_ID     NUMBER,
  PROFILERING_KODE        VARCHAR(30),
  CONSTRAINT "BRUKER_PROFILERING_KODEVERK_PK" PRIMARY KEY ("PROFILERING_KODE_ID"),
  CONSTRAINT "UNIQUE_CONSTRAINT_PROFILERING" UNIQUE ("PROFILERING_KODE")
);

CREATE TABLE BRUKER_PROFILERING (
  BRUKER_REGISTRERING_ID  NUMBER,
  PROFILERING_TYPE        VARCHAR(20) NOT NULL,
  VERDI                   VARCHAR(200) NOT NULL,
  CONSTRAINT "BRUKER_PROFILERING_PK" PRIMARY KEY ("BRUKER_REGISTRERING_ID", "PROFILERING_TYPE"),
  CONSTRAINT "PROFILERING_TYPE_FK" FOREIGN KEY ("PROFILERING_TYPE")
	  REFERENCES BRUKER_PROFILERING_KODEVERK ("PROFILERING_KODE")
);

INSERT INTO BRUKER_PROFILERING_KODEVERK VALUES (1, 'ALDER');
INSERT INTO BRUKER_PROFILERING_KODEVERK VALUES (2, 'ARB_SISTE_12_MND');
INSERT INTO BRUKER_PROFILERING_KODEVERK VALUES (3, 'OPPF_NAV_SISTE_12_MND');
INSERT INTO BRUKER_PROFILERING_KODEVERK VALUES (4, 'RESULTAT_PROFILERING');

CREATE TABLE BRUKER_REAKTIVERING (
  BRUKER_REAKTIVERING_ID     NUMBER,
  AKTOR_ID                   VARCHAR(20),
  REAKTIVERING_DATO          TIMESTAMP,
  CONSTRAINT "BRUKER_REAKTIVERING_PK" PRIMARY KEY ("BRUKER_REAKTIVERING_ID")
);

CREATE TABLE BEGRUNNELSE_KODEVERK (
  BEGRUNNELSE_ID     NUMBER,
  BEGRUNNELSE_KODE        VARCHAR(30),
  CONSTRAINT "BEGRUNNELSE_KODEVERK_PK" PRIMARY KEY ("BEGRUNNELSE_ID"),
  CONSTRAINT "UNIQUE_CONSTRAINT_BEGRUNNELSE" UNIQUE ("BEGRUNNELSE_KODE")
);

INSERT INTO BEGRUNNELSE_KODEVERK VALUES (1, 'MISTET_JOBBEN');
INSERT INTO BEGRUNNELSE_KODEVERK VALUES (2, 'HAR_SAGT_OPP');
INSERT INTO BEGRUNNELSE_KODEVERK VALUES (3, 'ER_PERMITTERT');
INSERT INTO BEGRUNNELSE_KODEVERK VALUES (4, 'JOBB_OVER_2_AAR');
INSERT INTO BEGRUNNELSE_KODEVERK VALUES (5, 'ALDRI_HATT_JOBB');
INSERT INTO BEGRUNNELSE_KODEVERK VALUES (6, 'VIL_BYTTE_JOBB');
INSERT INTO BEGRUNNELSE_KODEVERK VALUES (7, 'USIKKER_JOBBSITUASJON');
INSERT INTO BEGRUNNELSE_KODEVERK VALUES (8, 'VIL_FORTSETTE_I_JOBB');
