ALTER TABLE BRUKER_PROFILERING MODIFY PROFILERING_TYPE VARCHAR(30);

UPDATE BRUKER_PROFILERING_KODEVERK
SET PROFILERING_KODE = 'ARB_6_AV_SISTE_12_MND'
WHERE PROFILERING_KODE_ID = 2;

DELETE FROM BRUKER_PROFILERING_KODEVERK
WHERE PROFILERING_KODE_ID = 3;

UPDATE BRUKER_PROFILERING_KODEVERK
SET PROFILERING_KODE_ID = 3
WHERE PROFILERING_KODE_ID = 4;