UPDATE BRUKER_REGISTRERING SET BEGRUNNELSE_FOR_REGISTRERING = 'USIKKER_JOBBSITUASJON' WHERE BEGRUNNELSE_FOR_REGISTRERING='-';
ALTER TABLE BRUKER_REGISTRERING ADD CONSTRAINT "BEGRUNNELSE_REGISTRERING_FK" FOREIGN KEY ("BEGRUNNELSE_FOR_REGISTRERING") REFERENCES BEGRUNNELSE_KODEVERK ("BEGRUNNELSE_KODE");
