CREATE SEQUENCE BRUKER_REGISTRERING_SEQ;

CREATE TABLE BRUKER_REGISTRERING (
  BRUKER_REGISTRERING_ID  NUMBER,
  AKTOR_ID                VARCHAR(20) NOT NULL,
  OPPRETTET_DATO          TIMESTAMP,
  ENIG_I_OPPSUMMERING     NUMBER(1,0),
  OPPSUMMERING            CLOB,
  BESVARELSE              CLOB,
  CONSTRAINT "BRUKER_REGISTRERING_PK" PRIMARY KEY ("BRUKER_REGISTRERING_ID")
);

CREATE INDEX BRUKER_REG_AKTOR_ID_INDEX ON BRUKER_REGISTRERING ("AKTOR_ID");