ALTER TABLE BRUKER_REGISTRERING ADD TEKSTER_FOR_BESVARELSE VARCHAR(4000);

UPDATE BRUKER_REGISTRERING SET TEKSTER_FOR_BESVARELSE='';

ALTER TABLE BRUKER_REGISTRERING MODIFY TEKSTER_FOR_BESVARELSE VARCHAR(4000) NOT NULL;

CREATE OR REPLACE VIEW DVH_BRUKER_REGISTRERING AS
  (
  SELECT
    BRUKER_REGISTRERING_ID,
    AKTOR_ID,
    OPPRETTET_DATO,
    YRKESPRAKSIS,
    NUS_KODE,
    YRKESBESKRIVELSE,
    KONSEPT_ID,
    case UTDANNING_BESTATT when 'JA' then 1 when 'NEI' then 0 else -1 end as UTDANNING_BESTATT,
    case UTDANNING_GODKJENT_NORGE when 'JA' then 1 when 'NEI' then 0 when 'VET_IKKE' then 2 else -1 end as UTDANNING_GODKJENT_NORGE,
    case HAR_HELSEUTFORDRINGER when 'JA' then 1 when 'NEI' then 0 else -1 end as HELSE_UTFORDRINGER,
    case ANDRE_UTFORDRINGER when 'JA' then 1 when 'NEI' then 0 else -1 end as ANDRE_UTFORDRINGER,
    BEGRUNNELSE_FOR_REGISTRERING,
    TEKSTER_FOR_BESVARELSE
  FROM BRUKER_REGISTRERING
);