CREATE OR REPLACE VIEW DVH_BRUKER_REGISTRERING AS
  (
  SELECT
    BRUKER_REGISTRERING_ID,
    AKTOR_ID,
    OPPRETTET_DATO,
    YRKESPRAKSIS,
    NUS_KODE,
    YRKESBESKRIVELSE,
    KONSEPT_ID,
    case UTDANNING_BESTATT when 'JA' then 1 when 'NEI' then 0 else -1 end as UTDANNING_BESTATT,
    case UTDANNING_GODKJENT_NORGE when 'JA' then 1 when 'NEI' then 0 when 'VET_IKKE' then 2 else -1 end as UTDANNING_GODKJENT_NORGE,
    case HAR_HELSEUTFORDRINGER when 'JA' then 1 when 'NEI' then 0 else -1 end as HELSE_UTFORDRINGER,
    case ANDRE_UTFORDRINGER when 'JA' then 1 when 'NEI' then 0 else -1 end as ANDRE_UTFORDRINGER,
    BEGRUNNELSE_FOR_REGISTRERING
  FROM BRUKER_REGISTRERING
);