UPDATE BRUKER_REGISTRERING SET ANDRE_UTFORDRINGER='INGEN_SVAR' WHERE ANDRE_UTFORDRINGER='-';
UPDATE BRUKER_REGISTRERING SET UTDANNING_BESTATT='INGEN_SVAR' WHERE UTDANNING_BESTATT='-';
UPDATE BRUKER_REGISTRERING SET UTDANNING_GODKJENT_NORGE='INGEN_SVAR' WHERE UTDANNING_GODKJENT_NORGE='-';
UPDATE BRUKER_REGISTRERING SET JOBBHISTORIKK='INGEN_SVAR' WHERE JOBBHISTORIKK='-';