ALTER TABLE SYKMELDT_REGISTRERING MODIFY OPPRETTET_DATO TIMESTAMP NOT NULL;
ALTER TABLE SYKMELDT_REGISTRERING MODIFY TEKSTER_FOR_BESVARELSE VARCHAR(4000) NOT NULL;
ALTER TABLE SYKMELDT_REGISTRERING MODIFY FREMTIDIG_SITUASJON VARCHAR(30) NOT NULL;