CREATE SEQUENCE OPPGAVE_SEQ START WITH 1000;

CREATE TABLE OPPGAVE
(
  ID NUMBER NOT NULL,
  AKTOR_ID VARCHAR(20) NOT NULL,
  OPPGAVETYPE VARCHAR(36) NOT NULL,
  EKSTERN_OPPGAVE_ID NUMBER NOT NULL,
  OPPRETTET TIMESTAMP NOT NULL,
  CONSTRAINT OPPGAVE_PK PRIMARY KEY (ID)
);