CREATE OR REPLACE VIEW DVH_SYKMELDT_REGISTRERING AS
  (
    SELECT
      SYKMELDT_REGISTRERING_ID,
      AKTOR_ID,
      OPPRETTET_DATO,
      FREMTIDIG_SITUASJON,
      TILBAKE_ETTER_52_UKER,
      NUS_KODE,
      case UTDANNING_BESTATT when 'JA' then 1 when 'NEI' then 0 else -1 end as UTDANNING_BESTATT,
      case UTDANNING_GODKJENT_NORGE when 'JA' then 1 when 'NEI' then 0 else -1 end as UTDANNING_GODKJENT_NORGE,
      ANDRE_UTFORDRINGER
    FROM SYKMELDT_REGISTRERING
  );
