CREATE SEQUENCE REGISTRERING_TILSTAND_SEQ START WITH 1000;

CREATE TABLE REGISTRERING_TILSTAND
(
  ID NUMBER NOT NULL,
  UUID VARCHAR(36) NOT NULL,
  BRUKER_REGISTRERING_ID NUMBER NOT NULL,
  OPPRETTET TIMESTAMP NOT NULL,
  SIST_ENDRET TIMESTAMP,
  STATUS VARCHAR(36) NOT NULL,
  CONSTRAINT PK_REGISTRERING_TILSTAND PRIMARY KEY (ID),
  CONSTRAINT UQ_UUID UNIQUE (UUID)
);