CREATE SEQUENCE INFO_OM_MEG_SEQ;

CREATE TABLE INFO_OM_MEG (
  INFO_OM_MEG_ID NUMBER,
  AKTOR_ID VARCHAR(20) NOT NULL,
  SPM_ID VARCHAR(30) NOT NULL,
  ALTERNATIV_ID VARCHAR(30),
  TEKST VARCHAR(500),
  ENDRET_AV VARCHAR(20),
  DATO TIMESTAMP(6) NOT NULL,

  CONSTRAINT "INFO_OM_MEG_PK" PRIMARY KEY ("INFO_OM_MEG_ID")
);