CREATE TABLE "SITUASJON_KODEVERK"
   (	"SITUASJON_ID" NUMBER,
	"SITUASJON_KODE" VARCHAR2(30 BYTE),
	 CONSTRAINT "SITUASJON_KODEVERK_PK" PRIMARY KEY ("SITUASJON_ID"),
    CONSTRAINT "UNIQUE_CONSTRAINT_SITUASJON" UNIQUE ("SITUASJON_KODE"));

INSERT INTO SITUASJON_KODEVERK VALUES (1, 'SAMME_ARBEIDSGIVER');
INSERT INTO SITUASJON_KODEVERK VALUES (2, 'SAMME_ARBEIDSGIVER_NY_STILLING');
INSERT INTO SITUASJON_KODEVERK VALUES (3, 'NY_ARBEIDSGIVER');
INSERT INTO SITUASJON_KODEVERK VALUES (4, 'USIKKER');
INSERT INTO SITUASJON_KODEVERK VALUES (5, 'INGEN_PASSER');

ALTER TABLE SYKMELDT_REGISTRERING ADD CONSTRAINT "SITUASJON_KODEVERK_FK" FOREIGN KEY ("FREMTIDIG_SITUASJON") REFERENCES SITUASJON_KODEVERK ("SITUASJON_KODE");

CREATE OR REPLACE VIEW DVH_SITUASJON_KODEVERK AS
  (
    SELECT SITUASJON_ID, SITUASJON_KODE FROM SITUASJON_KODEVERK
  );
