CREATE SEQUENCE MANUELL_REGISTRERING_SEQ;

CREATE TABLE MANUELL_REGISTRERING (
MANUELL_REGISTRERING_ID   NUMBER,
AKTOR_ID                  VARCHAR(20) NOT NULL,
VEILEDER_IDENT            VARCHAR(10) NOT NULL,
VEILEDER_ENHET_ID         VARCHAR(4) NOT NULL,
CONSTRAINT "MANUELL_REGISTRERING_PK" PRIMARY KEY ("MANUELL_REGISTRERING_ID")
);

CREATE INDEX MANUELL_REG_AKTOR_ID_INDEX ON MANUELL_REGISTRERING ("AKTOR_ID");
