CREATE TABLE "SITUASJON_KODEVERK"
   (	"SITUASJON_ID" NUMBER,
	"SITUASJON_KODE" VARCHAR(30),
	CONSTRAINT "SITUASJON_KODEVERK_PK" PRIMARY KEY ("SITUASJON_ID"),
  CONSTRAINT "UNIQUE_CONSTRAINT_SITUASJON" UNIQUE ("SITUASJON_KODE")
  );

INSERT INTO SITUASJON_KODEVERK VALUES (1, 'SAMME_ARBEIDSGIVER');
INSERT INTO SITUASJON_KODEVERK VALUES (2, 'SAMME_ARBEIDSGIVER_NY_STILLING');
INSERT INTO SITUASJON_KODEVERK VALUES (3, 'NY_ARBEIDSGIVER');
INSERT INTO SITUASJON_KODEVERK VALUES (4, 'USIKKER');
INSERT INTO SITUASJON_KODEVERK VALUES (5, 'INGEN_PASSER');

ALTER TABLE SYKMELDT_REGISTRERING ADD CONSTRAINT "SITUASJON_KODEVERK_FK" FOREIGN KEY ("FREMTIDIG_SITUASJON") REFERENCES SITUASJON_KODEVERK ("SITUASJON_KODE");

CREATE OR REPLACE VIEW DVH_SITUASJON_KODEVERK AS
  (
    SELECT SITUASJON_ID, SITUASJON_KODE FROM SITUASJON_KODEVERK
  );


CREATE TABLE "TILBAKE_BESVARELSE_KODEVERK"
   (	"TILBAKE_BESVARELSE_ID" NUMBER,
	"TILBAKE_BESVARELSE_KODE" VARCHAR(30),
	 CONSTRAINT "TILBAKE_KODEVERK_PK" PRIMARY KEY ("TILBAKE_BESVARELSE_ID"),
    CONSTRAINT "UNIQUE_CONSTRAINT_TILBAKE" UNIQUE ("TILBAKE_BESVARELSE_KODE"));

INSERT INTO TILBAKE_BESVARELSE_KODEVERK VALUES (1, 'JA_FULL_STILLING');
INSERT INTO TILBAKE_BESVARELSE_KODEVERK VALUES (2, 'JA_REDUSERT_STILLING');
INSERT INTO TILBAKE_BESVARELSE_KODEVERK VALUES (3, 'USIKKER');
INSERT INTO TILBAKE_BESVARELSE_KODEVERK VALUES (4, 'NEI');

ALTER TABLE SYKMELDT_REGISTRERING ADD CONSTRAINT "TILBAKE_KODEVERK_FK" FOREIGN KEY ("TILBAKE_ETTER_52_UKER") REFERENCES TILBAKE_BESVARELSE_KODEVERK ("TILBAKE_BESVARELSE_KODE");

CREATE OR REPLACE VIEW DVH_TILBAKE_KODEVERK AS
  (
    SELECT TILBAKE_BESVARELSE_ID, TILBAKE_BESVARELSE_KODE FROM TILBAKE_BESVARELSE_KODEVERK
  );
