CREATE SEQUENCE FORMIDLINGSGRUPPE_SEQ START WITH 1000;

CREATE TABLE FORMIDLINGSGRUPPE
(
  ID NUMBER NOT NULL,
  FOEDSELSNUMMER VARCHAR(11) NOT NULL,
  FORMIDLINGSGRUPPE VARCHAR(5) NOT NULL,
  FORMIDLINGSGRUPPE_ENDRET TIMESTAMP NOT NULL,
  CONSTRAINT FORMIDLINGSGRUPPE_PK PRIMARY KEY (ID)
);