INSERT INTO REGISTRERING_TILSTAND (ID, BRUKER_REGISTRERING_ID, OPPRETTET, SIST_ENDRET, STATUS)
Select REGISTRERING_TILSTAND_SEQ.nextval AS ID,
       br.BRUKER_REGISTRERING_ID         as BRUKER_REGISTRERING_ID,
       CURRENT_TIMESTAMP                 as OPPRETTET,
       NULL                              as SIST_ENDRET,
       'PUBLISERT_KAFKA'                 as STATUS
from BRUKER_REGISTRERING br
         left join REGISTRERING_TILSTAND RT on br.BRUKER_REGISTRERING_ID = RT.BRUKER_REGISTRERING_ID
where RT.STATUS is null