CREATE SEQUENCE GJELDER_FRA_DATO_SEQ START WITH 1000;

CREATE TABLE GJELDER_FRA_DATO (
    ID NUMBER,
    FOEDSELSNUMMER VARCHAR(20) NOT NULL,
    DATO DATE NOT NULL,
    BRUKER_REGISTRERING_ID NUMBER,
    OPPRETTET_DATO TIMESTAMP,
    CONSTRAINT "GJELDER_FRA_DATO_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "GJELDER_FRA_DATO_BRUKER_REGISTRERING_ID_FK" FOREIGN KEY("BRUKER_REGISTRERING_ID") REFERENCES BRUKER_REGISTRERING("BRUKER_REGISTRERING_ID")
);

CREATE INDEX GJELDER_FRA_DATO_FOEDSELSNUMMER_INDEX ON GJELDER_FRA_DATO ("FOEDSELSNUMMER");
