CREATE VIEW DVH_BRUKER_REGISTRERING AS (
  SELECT
    BRUKER_REGISTRERING_ID,
    AKTOR_ID,
    OPPRETTET_DATO,
    YRKESPRAKSIS,
    NUS_KODE,
    UTDANNING_BESTATT,
    UTDANNING_GODKJENT_NORGE
  FROM BRUKER_REGISTRERING
);