ALTER TABLE BRUKER_REGISTRERING DROP COLUMN SITUASJON;

ALTER TABLE BRUKER_REGISTRERING MODIFY OPPRETTET_DATO TIMESTAMP NOT NULL;
ALTER TABLE BRUKER_REGISTRERING MODIFY NUS_KODE VARCHAR(6) NOT NULL;
ALTER TABLE BRUKER_REGISTRERING MODIFY YRKESPRAKSIS VARCHAR(7) NOT NULL;
ALTER TABLE BRUKER_REGISTRERING MODIFY ENIG_I_OPPSUMMERING NUMBER(1,0) NOT NULL;
ALTER TABLE BRUKER_REGISTRERING MODIFY UTDANNING_BESTATT NUMBER(1,0) NOT NULL;
ALTER TABLE BRUKER_REGISTRERING MODIFY UTDANNING_GODKJENT_NORGE NUMBER(1,0) NOT NULL;
ALTER TABLE BRUKER_REGISTRERING MODIFY HAR_HELSEUTFORDRINGER NUMBER(1,0) NOT NULL;