ALTER TABLE BRUKER_REGISTRERING add YRKESBESKRIVELSE VARCHAR(200);
ALTER TABLE BRUKER_REGISTRERING add KONSEPT_ID NUMBER;

UPDATE BRUKER_REGISTRERING
SET YRKESBESKRIVELSE=-1, KONSEPT_ID=-1
WHERE YRKESBESKRIVELSE IS NULL AND KONSEPT_ID IS NULL;

ALTER TABLE BRUKER_REGISTRERING MODIFY YRKESBESKRIVELSE VARCHAR(200) NOT NULL;
ALTER TABLE BRUKER_REGISTRERING MODIFY KONSEPT_ID NUMBER NOT NULL;

DROP VIEW DVH_BRUKER_REGISTRERING;
CREATE VIEW DVH_BRUKER_REGISTRERING AS (
  SELECT
    BRUKER_REGISTRERING_ID,
    AKTOR_ID,
    OPPRETTET_DATO,
    YRKESPRAKSIS,
    NUS_KODE,
    -1 AS UTDANNING_BESTATT,
    -1 AS UTDANNING_GODKJENT_NORGE,
    YRKESBESKRIVELSE,
    KONSEPT_ID
  FROM BRUKER_REGISTRERING
);