kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbregistrering
  namespace: paw
  labels:
    team: paw
spec:
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
  tokenx:
    enabled: true
  envFrom:
    - configmap: loginservice-idporten
  image: {{image}}
  ingresses:
    - https://veilarbregistrering-fss.dev.intern.nav.no
    - https://veilarbregistrering-q1.dev.adeo.no
    - https://veilarbregistrering-q1.nais.preprod.local
    - https://app-q1.adeo.no/veilarbregistrering
  env:
    - name: AAREG_REST_API
      value: https://aareg-services-q1.dev.intern.nav.no/api
    - name: AAREG_CLUSTER
      value: dev-fss
    - name: AAREG_APPNAME
      value: aareg-services-nais-q1
    - name: AAD_DISCOVERY_URL
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
    - name: VEILARBLOGIN_AAD_CLIENT_ID
      value: 65a379be-d708-4e63-b6a0-df52efdf695f
    - name: VEILARBOPPFOLGINGAPI_URL
      value: https://veilarboppfolging-q1.nais.preprod.local/veilarboppfolging/api
    - name: VEILARBOPPFOLGINGAPI_CLUSTER
      value: dev-fss
    - name: VEILARBARENA_URL
      value: https://veilarbarena.dev.intern.nav.no/veilarbarena/api
    - name: VEILARBARENA_CLUSTER
      value: dev-fss
    - name: PAW_PROXY_CLUSTER
      value: dev-fss
    - name: ABAC_PDP_ENDPOINT_URL
      value: https://abac-veilarb-q1.dev.intern.nav.no/application/asm-pdp/authorize
    - name: UNLEASH_API_URL
      value: https://unleash.nais.io/api/
    - name: NORG2_URL
      value: https://app-q1.adeo.no/norg2
    - name: OPPGAVE_URL
      value: https://oppgave.nais.preprod.local
    - name: OPPGAVE_CLUSTER
      value: dev-fss
    - name: DIGDIR_KRR_PROXY_BASE_URL
      value: https://digdir-krr-proxy.dev.intern.nav.no/rest/
    - name: DIGDIR_KRR_CLUSTER
      value: dev-gcp
    - name: PDL_URL
      value: http://pdl-api.default.svc.nais.local
    - name: PDL_CLUSTER
      value: dev-fss
    - name: ENHET_URL
      value: https://modapp-q1.adeo.no/ereg
    - name: KAFKA_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: KAFKA_SCHEMA
      value: http://kafka-schema-registry.tpa.svc.nais.local:8081
    - name: ARENA_ORDS_API
      value: https://arena-ords-q1.dev.intern.nav.no
    - name: ARENA_ORDS_TOKEN_PROVIDER
      value: https://arena-ords-q1.dev.intern.nav.no
  leaderElection: true
  kafka:
    pool: nav-dev
  liveness:
    initialDelay: 60
    path: veilarbregistrering/internal/isAlive
    port: 8080
  port: 8080
  prometheus:
    enabled: true
    path: veilarbregistrering/internal/prometheus
  readiness:
    initialDelay: 60
    path: veilarbregistrering/internal/isReady
    port: 8080
  replicas:
    cpuThresholdPercentage: 85
    max: 6
    min: 2
  resources:
    limits:
      cpu: "3"
      memory: 3048Mi
    requests:
      cpu: "1"
      memory: 2048Mi
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/veilarbregistrering_q1-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /oracle/data/dev/config/veilarbregistrering_q1
        mountPath: /var/run/secrets/nais.io/oracle_config
      - kvPath: /serviceuser/data/dev/srvveilarbregistrering
        mountPath: /var/run/secrets/nais.io/serviceuser_creds
      - kvPath: /kv/preprod/fss/veilarbregistrering/q1
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: pto-proxy
          namespace: pto
          cluster: dev-gcp
        - application: paw-proxy
        - application: veilarbperson
          namespace: pto
        - application: veilarbdirigent
          namespace: pto
        - application: dp-oppslag-arbeidssoker
          namespace: teamdagpenger
        - application: familie-ef-proxy
          namespace: teamfamilie
          cluster: dev-fss

    outbound:
      rules:
        - application: aareg-services-nais-q1
          namespace: arbeidsforhold
          cluster: dev-fss
