kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbregistrering
  namespace: paw
  labels:
    team: paw
spec:
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  tokenx:
    enabled: true
  envFrom:
    - secret: veilarbregistrering
    - secret: veilarbregistrering-unleash-api-token
  image: {{image}}
  ingresses:
    - https://veilarbregistrering.intern.dev.nav.no
  env:
    - name: AAREG_REST_API
      value: https://aareg-services-q1.dev-fss-pub.nais.io/api
    - name: AAREG_CLUSTER
      value: dev-fss
    - name: AAREG_APPNAME
      value: aareg-services-nais-q1
    - name: AAD_DISCOVERY_URL
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
    - name: VEILARBOPPFOLGINGAPI_URL
      value: https://veilarboppfolging.dev-fss-pub.nais.io/veilarboppfolging/api
    - name: VEILARBOPPFOLGINGAPI_CLUSTER
      value: dev-fss
    - name: VEILARBARENA_URL
      value: https://veilarbarena.dev-fss-pub.nais.io/veilarbarena/api
    - name: VEILARBARENA_CLUSTER
      value: dev-fss
    - name: VEILARBREGISTRERING_ONPREM_URL
      value: https://paw-proxy.dev-fss-pub.nais.io/veilarbregistrering
    - name: PAW_PROXY_CLUSTER
      value: dev-fss
    - name: ABAC_PDP_ENDPOINT_URL
      value: https://abac-veilarb-proxy.dev-fss-pub.nais.io/api/proxy/abac
    - name: ABAC_CLUSTER
      value: dev-fss
    - name: UNLEASH_API_URL
      value: https://unleash.nais.io/api/
    - name: NORG2_URL
      value: https://norg2.dev-fss-pub.nais.io/norg2
    - name: OPPGAVE_URL
      value: https://oppgave-q1.dev-fss-pub.nais.io
    - name: OPPGAVE_CLUSTER
      value: dev-fss
    - name: DIGDIR_KRR_PROXY_BASE_URL
      value: http://digdir-krr-proxy.team-rocket/rest/
    - name: DIGDIR_KRR_CLUSTER
      value: dev-gcp
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io
    - name: PDL_CLUSTER
      value: dev-fss
    - name: ENHET_URL
      value: https://ereg-services-q1.dev-fss-pub.nais.io/ereg
    - name: SPRING_PROFILES_ACTIVE
      value: gcp
    - name: UNLEASH_SERVER_API_URL
      value: https://paw-unleash-api.nav.cloud.nais.io/api
  leaderElection: true
  kafka:
    pool: nav-dev
  liveness:
    initialDelay: 60
    path: veilarbregistrering/internal/isAlive
    port: 8080
  port: 8080
  prometheus:
    enabled: true
    path: veilarbregistrering/internal/prometheus
  readiness:
    initialDelay: 60
    path: veilarbregistrering/internal/isReady
    port: 8080
  replicas:
    cpuThresholdPercentage: 85
    max: 6
    min: 2
  resources:
    limits:
      cpu: "3"
      memory: 3048Mi
    requests:
      cpu: "1"
      memory: 2048Mi
  webproxy: true
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: arbeidssokerregistrering
        - application: arbeidssokerregistrering-for-veileder
        - application: aia-backend
        - application: paw-reaktiver-arbeidssoker
        - application: veilarbperson
          namespace: pto
          cluster: dev-fss
        - application: veilarbdirigent
          namespace: pto
          cluster: dev-fss
        - application: familie-ef-sak
          namespace: teamfamilie
        - application: meroppfolging-frontend
          namespace: team-esyfo
        - application: meroppfolging-backend
          namespace: team-esyfo
        - application: azure-token-generator
          namespace: aura
        - application: tokenx-token-generator
          namespace: aura
    outbound:
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: aareg-services-q1.dev-fss-pub.nais.io
        - host: veilarboppfolging.dev-fss-pub.nais.io
        - host: veilarbarena.dev-fss-pub.nais.io
        - host: paw-proxy.dev-fss-pub.nais.io
        - host: abac-veilarb-proxy.dev-fss-pub.nais.io
        - host: norg2.dev-fss-pub.nais.io
        - host: oppgave-q1.dev-fss-pub.nais.io
        - host: ereg-services-q1.dev-fss-pub.nais.io
        - host: paw-unleash-api.nav.cloud.nais.io
      rules:
        - application: aareg-services-nais-q1
          namespace: arbeidsforhold
          cluster: dev-fss
        - application: abac-veilarb-proxy
          namespace: pto
          cluster: dev-fss
        - application: digdir-krr-proxy
          namespace: team-rocket
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: db-f1-micro
        diskSize: 10
        diskAutoresize: true
        pointInTimeRecovery: true
        maintenance:
          day: 1
          hour: 4
        databases:
          - name: veilarbregistrering
            envVarPrefix: PAWVEILARBREGISTRERING
            users:
              - name: dataprodukt_paw
